#!/bin/bash

set -e

echo_red() {
    echo -e "\r\033[31m$1\033[0m"
}
echo_green() {
    echo -e "\r\033[32m$1\033[0m"
}
echo_blue() {
    echo -e "\r\033[36m$1\033[0m"
}


PATH_PWD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# 为系统添加set-lcd命令
chmod +x $PATH_PWD/set-lcd
bin_path="/usr/bin/set-lcd"

if [ -f $bin_path ]; then
    rm $bin_path
fi
if [ ! -e $bin_path ]; then
    ln -s ${PATH_PWD}/set-lcd ${bin_path}
fi
if [[ ! -d /etc/bash_completion.d/ ]]; then
    mkdir /etc/bash_completion.d/
fi
cp ${PATH_PWD}/completion.sh  /etc/bash_completion.d/set-lcd

bash_str="source /etc/bash_completion.d/set-lcd"
if ! grep -q  ${bash_str}  /etc/bash.bashrc; then
    echo ${bash_str} >> /etc/bash.bashrc
fi

source ${PATH_PWD}/compile_driver.sh

echo_green "[OK]\t set-lcd install ready"

