#!/bin/bash
if [ -z "$1" ]; then
    echo -e "\033[31m[Error]\033[0m"
    echo "please choose tft"
    exit 1
fi
if [ -z "$2" ]; then
    echo -e "\033[31m[Error]\033[0m"
    echo "please choose Function"
    exit 1
fi


set -e

PATH_PWD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
PATH_CONF="${PATH_PWD}/conf"
PATH_TFT="${PATH_PWD}/tft"
PATH_DTB="${PATH_PWD}/dtb"


TFT_NAME=$1
OPT_TFT_SETTING="${PATH_TFT}/${TFT_NAME}"
source $OPT_TFT_SETTING


# 更新设备树文件
_install_modules() {
    modules_file="/etc/modules"
    if ! grep -q "^${module_tft}$" "$modules_file"; then
        echo "${module_tft}" >> "$modules_file"
    fi
    if ! grep -q "^${module_touch}$" "$modules_file"; then
        echo "${module_touch}" >> "$modules_file"
    fi

    config_file="/boot/config.txt"
    if grep -q "^overlays=" "$config_file"; then
    if ! grep -q "^overlays=.*${dtb_name}" "$config_file"; then
        sed -i "s/^overlays=/&${dtb_name} /" "$config_file"
    fi
    else
        echo "overlays=${dtb_name}" >> "$config_file"
    fi


    dts_files=$(find "$PATH_DTB" -type f -name "*${dtb_name}.dts")
    for dts_file in $dts_files; do
        dtbo_file="${dts_file%.dts}.dtbo"
        dtc -@  -I dts -O dtb -o "$dtbo_file" "$dts_file"
    done

    overlays_folder="/boot/overlays"
    dtb_files=$(find "$PATH_DTB" -type f -name "*${dtb_name}.dtbo")
    for file in $dtb_files; do
        cp "$file" "$overlays_folder"
    done

}

_dtb_replace() {
    local name=$1
    local value=$2

    local searchString="$name = <[0-9]*>"
    local replaceString="$name = <$value>"

    dts_files=$(find "$PATH_DTB" -type f -name "*${dtb_name}.dts")
    for dts_file in $dts_files; do
        dtbo_file="${dts_file%.dts}.dtbo"
        sed -i "s/$searchString/$replaceString/g" $dts_file
        dtc -@  -I dts -O dtb -o "$dtbo_file" "$dts_file"
    done
}

set_rotate_switch="0 90 180 270"
set_rotate() {
    OPT_operate=$1

    if [[ ! $set_rotate_switch =~ (^|[[:space:]])$OPT_operate($|[[:space:]]) ]]; then
        echo -e "\033[31m[Error]\033[0m"
        echo "error angle"
        exit 1
    fi

    _dtb_replace "rotate" $OPT_operate 
    cp -rf "${PATH_CONF}/calibration.conf-${TFT_NAME}-${OPT_operate}"  /etc/X11/xorg.conf.d/99-calibration.conf
    
    _install_modules
}

# -h() {
#     echo -e "${help_str}"
# }

install_only_fb() {
    _install_modules
    target_file="/usr/share/X11/xorg.conf.d/99-fbdev.conf"
    if [ -f "$target_file" ]; then
        rm -rf  $target_path
    fi
    set_rotate 270
}

install_desktop() {
    target_path="/usr/share/X11/xorg.conf.d/"
    if [ -d "$target_path" ]; then
        cp ${PATH_CONF}/99-fbdev.conf $target_path
        cp ${PATH_CONF}/10-evdev.conf $target_path
    fi
    cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
    set_rotate 270
}

remove() {
    modules_file="/etc/modules"
    sed -i "/^${module_tft}/d" "$modules_file"
    sed -i "/^${module_touch}/d" "$modules_file"

    config_file="/boot/config.txt"
    sed -i "/^overlays=/ s/${dtb_name}//g" "$config_file"

    target_file="/usr/share/X11/xorg.conf.d/99-fbdev.conf"
    if [ -f "$target_file" ]; then
        rm -rf  $target_path
    fi

}


FUNCTION_NAME=$2
ARGUMENT=$3
$FUNCTION_NAME $ARGUMENT

if [[ $? -ne 0 ]]; then
    exit 1
fi
echo -e "\033[32m[ok]\033[0m"